path:
    # raw_path: "/content/drive/MyDrive/ZaloAI_Hum_To_Song/preprocessed"
    # preprocessed_path: "/content/drive/MyDrive/ZaloAI_Hum_To_Song/preprocessed"
    # temp_dir: "/content/drive/MyDrive/ZaloAI_Hum_To_Song/temp_dir"
    # visualization_path: "/content/drive/MyDrive/ZaloAI_Hum_To_Song/visualization"

    raw_path: "/hum2song/preprocessed"
    preprocessed_path: "/hum2song/preprocessed"
    temp_dir: "/hum2song/temp_dir"
    visualization_path: "/hum2song/visualization"
preprocessing:
    val_size: 512
    split_win_size: 610
    split_stride_size: 32
    audio:
        sampling_rate: 16000
        max_wav_value: 32767.0
    stft:
        filter_length: 1024
        hop_length: 256
        win_length: 1024
    mel:
        n_mel_channels: 80
        mel_fmin: 0
        mel_fmax: 8000
